# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ea636ed605720de6bd541ba22e1cd2f793042ebae8a686a443c09c190e142b522b0cdd4d5a38b5e929d36be9557091f451120a1aca54d10a6dfdc9f582ba3ba

test:
  secret_key_base: 1a2d9a59c34eee21f09e992d0f3ca9cb024d1dd405ee6fd1c5e3cc6c3067d66362a616beeb959f154c38693d3745e5113492d9a85122ab96f3d9f16e8be507bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
